version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-api
    image: txpool-checker-api
    ports:
      - "8081:8081"

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-web
    image: txpool-checker-web
    ports:
      - "8080:8080"