# Step 1: Modules caching
FROM golang:1.19.2-alpine3.16 as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.19.2-alpine3.16 as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /bin/app ./cmd/api

# Step 3: ca-certificates
FROM alpine:3.6 as alpine
RUN apk add -U --no-cache ca-certificates

# Step 4: Final
FROM scratch

EXPOSE 8081

# GOPATH for scratch images is /
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /bin/app /app
CMD ["/app"]